// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA67qZIS2Z4eqZdrHHaOjl3tOikaobLJg4',
    appId: '1:907241970128:web:d8f921c3447432fe8801d5',
    messagingSenderId: '907241970128',
    projectId: 'skillswap-90112',
    authDomain: 'skillswap-90112.firebaseapp.com',
    storageBucket: 'skillswap-90112.firebasestorage.app',
    measurementId: 'G-9KM27491ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWf3nDPHi465QNMQvz_hevQPz9iMyKJGA',
    appId: '1:907241970128:android:eac7b724e768b9748801d5',
    messagingSenderId: '907241970128',
    projectId: 'skillswap-90112',
    storageBucket: 'skillswap-90112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtFRm5UGm-Kw9kueGIWxhaXJDIojp6eqQ',
    appId: '1:907241970128:ios:ff871f23e0c8a51f8801d5',
    messagingSenderId: '907241970128',
    projectId: 'skillswap-90112',
    storageBucket: 'skillswap-90112.firebasestorage.app',
    iosClientId: '907241970128-8cji0mfgv8cj0lid3d63r75alh669eeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtFRm5UGm-Kw9kueGIWxhaXJDIojp6eqQ',
    appId: '1:907241970128:ios:ff871f23e0c8a51f8801d5',
    messagingSenderId: '907241970128',
    projectId: 'skillswap-90112',
    storageBucket: 'skillswap-90112.firebasestorage.app',
    iosClientId: '907241970128-8cji0mfgv8cj0lid3d63r75alh669eeu.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA67qZIS2Z4eqZdrHHaOjl3tOikaobLJg4',
    appId: '1:907241970128:web:06b3eaa022df53b38801d5',
    messagingSenderId: '907241970128',
    projectId: 'skillswap-90112',
    authDomain: 'skillswap-90112.firebaseapp.com',
    storageBucket: 'skillswap-90112.firebasestorage.app',
    measurementId: 'G-GSNP4T5GSQ',
  );
}
